# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b9a0a0437933a3402adf9b88abf6acfce8fec8c9c40e959ec881083b4550831f6586693509b848e8a3e5c345034b5da5a066b3d6e90257fea69d4a05cc68f4

test:
  secret_key_base: 4a8a2e6786830b61b68386af8a869bb72d2753eec7032157c00b3d621317f7fb424264167fc9db13012a2dc8a1491aeeb71d174538f7acdba9a97608e5778ddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
